global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'notifly-api'
    static_configs:
      - targets: ['notifly-api:8080']
    metrics_path: '/api/prometheus'

  - job_name: 'notifly-worker'
    static_configs:
      - targets: ['notifly-worker:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
